### ISSUE TITLE
Trouble to contact you.

### ISSUE THREAD

**Issue by Alcantor** [t4eeditor/Binary-Releases#1]
I have a hard time trying to contact you ;-) I've tried the email address of lotus-forum.de and lotustalk... Well I've finally got an access to your wiki, that is a goldmine. Thanks you for all the work you've done.

I've could successfully patch and flash my Lotus Exige. But I've see, you have done much more! Like updating the cluster and X-Ray the T4e... Is there a way to all that good stuff?

**Comment by cloudn1ne** [comment]
I just uploaded pretty much all i ever created for the t4e topic - hope you find something useful contained. if u have specific questions feel free to ask but it has been a long time and i probably dont remember half of it anymore

**Comment by Alcantor** [comment]
Many Thanks!

**Comment by cloudn1ne** [comment]
i opened the wiki as well
